### ISSUE TITLE
Missing dependency on Java 6 runtime.

### ISSUE THREAD

**Issue by rossmcf** [boxen/puppet-phpstorm#8]
When starting PHPStorm for the first time after installation, it requests that the legacy Java 6 runtime be installed. Could this be added as a dependency, please?

Thanks,
Ross

**Comment by hussfelt** [comment]
:+1:

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
